# Dependencies
markdown:         redcarpet
highlighter:      rouge
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

# Permalinks
# permalink: /:year-:month-:day-:title/
permalink:        pretty
future:           true
# relative_permalinks: true

# Setup
title:            VagarntPi Blog
tagline:          'JavaScript, Front-End, Back-End, Full Stack, Linux, 筆記, 生活札記'
description:      '生活札記，記錄些學習筆記和生活'
baseurl:          /

author:           VagarntPi
url:              http://vagrantpi.github.io

paginate:         5


# Custom vars
version:          2.1.0

twitter:
  username:       VagrantPi

github:
  repo:           https://github.com/poole/hyde

  logo:           /public/favicon.ico
# Gems
gems:             
  - jekyll-paginate
  - jekyll-seo-tag


social:
  links:
    - https://github.com/VagrantPi
    - https://twitter.com/VagrantPi
    - https://www.facebook.com/VagrantPi
