# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink: /:year-:month-:day-:title/
permalink:        pretty
future: true
# relative_permalinks: true

# Setup
title:            VagarntPi Blog
tagline:          '生活札記'
description:      '生活札記'
url:              http://vagrantpi.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

  host: 0.0.0.0
  port: 4000

# Gems
  gems: [jekyll-paginate]
